name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false

            - name: Cache node_modules
              uses: actions/cache@v4
              id: cache-nodemodules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Install dependencies
              run: pnpm install

            - name: Run lint
              run: pnpm lint
